# Automatically generated file. DO NOT MODIFY
#
# This file is generated by device/xiaomi/ruby/setup-makefiles.sh

LOCAL_PATH := $(call my-dir)

ifeq ($(TARGET_DEVICE),ruby)

$(call add-radio-file-sha1-checked,radio/audio_dsp.img,e92c766b7001595a9ca943c44846fca03ae6fb71)
$(call add-radio-file-sha1-checked,radio/cam_vpu1.img,0b2bb9afec35db8e3df473839f7e532a7ed76646)
$(call add-radio-file-sha1-checked,radio/cam_vpu2.img,fafd68f92ee3dfcc3961a06f2fdc2618e026fe5e)
$(call add-radio-file-sha1-checked,radio/cam_vpu3.img,a0ae489e3f12d8fc50b5cc49b567de168624460c)
$(call add-radio-file-sha1-checked,radio/dpm.img,c24df95772d1f65a33087ac161cf335916bfc807)
$(call add-radio-file-sha1-checked,radio/gz.img,d4aa29b08fa2418f87a82c49e31268ad5e2dc418)
$(call add-radio-file-sha1-checked,radio/lk.img,6cf00f640a00904dfbcc34da222b00863129571a)
$(call add-radio-file-sha1-checked,radio/logo.img,3b0ab50a9fd92ca48931135f0a0bc3513ca8ae98)
$(call add-radio-file-sha1-checked,radio/mcupm.img,2aee6f3adae077009b7c10530f574f7944252f51)
$(call add-radio-file-sha1-checked,radio/md1img.img,907aa001492180ed702d4bbc7465cdccb2ce3979)
$(call add-radio-file-sha1-checked,radio/pi_img.img,0ce4f58f2af0c7036bbc949b1a5b3fd97e55ff08)
$(call add-radio-file-sha1-checked,radio/preloader_raw.img,cd7f2051bd95498070de5e0c3ab92ed84d792411)
$(call add-radio-file-sha1-checked,radio/scp.img,144ca94893e8998c4ebfa897c7570392f3c7b831)
$(call add-radio-file-sha1-checked,radio/spmfw.img,f740e5892cf2e71f0f29306a07abc2d2e6c34dcf)
$(call add-radio-file-sha1-checked,radio/sspm.img,ad5190973e71e21bfd87bea4606e2c23ac448f63)
$(call add-radio-file-sha1-checked,radio/tee.img,a10f9a967035996ee39e9075eab3adb92a65f003)

endif
